version: 2

project_name: updo

force_token: github

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make build-lambda

builds:
  - binary: updo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - binary

nfpms:
  - package_name: updo
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    maintainer: "pgagnidze <pgagnidze@pm.me>"
    vendor: "Owloops"
    homepage: "https://github.com/Owloops/updo"
    license: "MIT"
    description: "Uptime monitoring CLI tool with alerting and advanced settings"
    section: "net"
    priority: "optional"

brews:
  - name: updo
    description: Uptime monitoring CLI tool with alerting and advanced settings
    homepage: https://github.com/Owloops/updo
    license: MIT
    repository:
      owner: Owloops
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

changelog:
  use: github
