global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Remote write configuration is handled by the --web.enable-remote-write-receiver flag
# This enables the /api/v1/write endpoint for receiving data from updo